<?php

    $title = "Marmitas - Dona Rita";

    $cardapio = array(
        0 => array('id'=>'1',
		'titulo'=>'Natural',
		'descricao'=>'O prato conta com apenas ingredientes de origem natural em sua composição: tomate, açúcar, vinagre, sal, cebola e aroma natural, proveniente de ervas e especiarias, sem processos químicos em sua obtenção. Dona Rita vai te surpreender, experimente.',
		'imagem'=>'img/img1.jpg',
		'ingredientes'=>'Alface americana, tomate, cebola, pimentão, repolho, kiwi, manga, arroz.',
		'preco'=>'R$ 20,00'),
        1 => array('id'=>'2',
		'titulo'=>'Vegana',
		'descricao'=>'O prato vegano não possui alimentos de origem animal, como carne (incluindo peixes e moluscos), laticínios, ovos e mel. Essa opção se destaca pelo sabor especial que só Dona Rita sabe fazer.',
		'imagem'=>'img/img2.jpg',
		'ingredientes'=>'Alface, repolho, tomate, pimentão, brócoles, couve, arroz integral, especiarias.',
		'preco'=>'R$ 22,50'),
        2 => array('id'=>'3',
		'titulo'=>'Vegetariana',
		'descricao'=>'O prato é preparado segundo os padrões vegetarianos, e que portanto não incluem carne ou qualquer outros produtos feitos a partir de tecido animal. Dona Rita garante uma ótima e saborosa refeição, experimente!',
		'imagem'=>'img/img3.jpg',
		'ingredientes'=>'Alface americana, tomate, cebola, pimentão, repolho, kiwi, manga, arroz, feijão verde.',
		'preco'=>'R$ 21,00'),
        3 => array('id'=>'4',
		'titulo'=>'Frango grelhado com batata',
		'descricao'=>'O frango grelhado é uma ótima pedida para as refeições cotidianas. Confira a receita de Dona Rita!',
		'imagem'=>'img/img4.jpg',
		'ingredientes'=>'Peito de frango grelhado, batata, arroz branco e brócoles.',
		'preco'=>'R$ 19,00'),
        4 => array('id'=>'5',
		'titulo'=>'Pene com almôndegas',
		'descricao'=>'O prato é ideal para seu domingo. O macarrão pene com almôndegas para o almoço pode ficar ainda mais agradável e sabroso se for o de Dona Rita. Peça já o seu.',
		'imagem'=>'img/img5.jpg',
		'ingredientes'=>'Macarrão pene, molho de tomate, almôndegas, tomates cereja.',
		'preco'=>'R$ 19,00'),
		5 => array('id'=>'6',
		'titulo'=>'Frango assado',
		'descricao'=>'Esse prato é uma de nossas receitas mais queridas, frango assado com batata e maionese é de dar água na boca. Venha conferir!',
		'imagem'=>'img/img6a.png',
		'ingredientes'=>'Coxa e sobrecoxa de frango assado, arroz, macarrão e batata.',
		'preco'=>'R$ 19,50'),
		6 => array('id'=>'7',
		'titulo'=>'Salada',
		'descricao'=>'O prato é uma especialidade de Dona Rita. Não é uma salada qualquer. As folhagens são complementadas por tomatinhos, romã e carambola, além de molho de mostarda. Não deixe de experimentar.',
		'imagem'=>'img/img7.jpg',
		'ingredientes'=>'Alface americana, tomate, pepino, kiwi, laranja, arroz vermelho, fiambre bovino, molhos especiais.',
		'preco'=>'R$ 20,00'),
		7 => array('id'=>'8',
		'titulo'=>'Moda da casa',
		'descricao'=>'Dona Rita tem essa excelente receita que é sua especialdade. O prato esbanja variedade de vegetais e carnes deliciosas. Venha conferir! Peça já a sua!!',
		'imagem'=>'img/img8.jpg',
		'ingredientes'=>'Feijão, arroz, macarrão, bifes, batata frita, ovos, purê e salada especial.',
		'preco'=>'R$ 23,00'),
    );